[project]
name = "gis-datasets"
version = "0.1.0"
description = "The GisDatasets module"
authors = []
requires-python = ">=3.12"
dependencies = [
    "simple-module-core",
    "simple-module-db",
    "simple-module-hosting",
]

[project.entry-points.simple_module]
gis_datasets = "gis_datasets.module:GisDatasetsModule"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
simple-module-core = { workspace = true }
simple-module-db = { workspace = true }
simple-module-hosting = { workspace = true }
