"""{{MODULE_NAME}} module — generated by `sm create-module`."""

from __future__ import annotations

import importlib.resources
from pathlib import Path

from fastapi import APIRouter
from simple_module_core import ModuleBase, ModuleMeta


class {{MODULE_NAME}}Module(ModuleBase):
    meta = ModuleMeta(
        name="{{MODULE_NAME}}",
        route_prefix="/api/{{MODULE_SLUG}}",
        view_prefix="/{{MODULE_SLUG}}",
        depends_on=[],
        version="0.1.0",
        requires_framework=">=1.0,<2.0",
    )

    def register_routes(self, api_router: APIRouter, view_router: APIRouter) -> None:
        from {{PACKAGE_NAME}}.endpoints.api import router as api

        api_router.include_router(api)

    def static_mounts(self) -> dict[str, Path]:
        """Expose pre-built frontend assets when they exist.

        Returns an empty dict when ``static/dist/`` hasn't been built yet,
        so ``uv run pytest`` works during development. In production, the
        wheel ships the built bundle via ``force-include`` in
        ``pyproject.toml`` and the host mounts it at
        ``/modules/{{MODULE_SLUG}}/static``.
        """
        pkg_root = Path(str(importlib.resources.files("{{PACKAGE_NAME}}")))
        dist = pkg_root / "static" / "dist"
        if not dist.is_dir():
            return {}
        return {"/modules/{{MODULE_SLUG}}/static": dist}
