services:
  app:
    build:
      context: .
      dockerfile: docker/host.Dockerfile
    env_file:
      - path: .env
        required: false
    environment:
      # Containers serve the built bundle; development mode would emit
      # asset tags pointing at the (absent) Vite dev server.
      SM_ENVIRONMENT: production
      # The scaffold's migrations were autogenerated against SQLite, so the
      # container stays on SQLite too (a migration history is dialect-frozen
      # at autogenerate time). The named volume keeps the DB across restarts.
      # To move to Postgres, re-scaffold with --db postgres or add a postgres
      # service and regenerate migrations against it.
      SM_DATABASE_URL: sqlite+aiosqlite:////app/data/app.db
{{APP_EXTRA_ENV}}    ports:
      - "8000:8000"
    volumes:
      - appdata:/app/data
