"""Setting service protocol — the public contract other modules depend on."""

from __future__ import annotations

from typing import Protocol

from settings.contracts.schemas import (
    SettingCreate,
    SettingOut,
    SettingUpdate,
    SettingUpsert,
)


class ISettingService(Protocol):
    """Interface for key/value setting operations."""

    async def list_all(self) -> list[SettingOut]: ...
    async def get_by_id(self, setting_id: int) -> SettingOut | None: ...
    async def get_by_key(self, key: str) -> SettingOut | None: ...
    async def get_value(self, key: str, default: str | None = None) -> str | None: ...
    async def create(self, data: SettingCreate) -> SettingOut: ...
    async def update(self, setting_id: int, data: SettingUpdate) -> SettingOut | None: ...
    async def upsert_by_key(self, key: str, data: SettingUpsert) -> SettingOut: ...
    async def delete(self, setting_id: int) -> bool: ...
    async def delete_by_key(self, key: str) -> bool: ...
