[project]
name = "simple-module-host"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "simple-module-hosting",
    "auth",
    "dashboard",
    "products",
    "permissions",
    "background-tasks",
    "file-storage",
    "python-multipart>=0.0.6",
]

[tool.uv.sources]
simple-module-hosting = { workspace = true }
auth = { workspace = true }
products = { workspace = true }
dashboard = { workspace = true }
permissions = { workspace = true }
background-tasks = { workspace = true }
file-storage = { workspace = true }
