[project]
name = "simple-module-host"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "simple-module-hosting",
    "simple-module-auth",
    "simple-module-dashboard",
    "simple-module-products",
    "simple-module-datasets",
    "simple-module-permissions",
    "simple-module-background-tasks",
    "simple-module-file-storage",
    "simple-module-settings",
    "simple-module-feature-flags",
    "python-multipart>=0.0.6",
]

[tool.uv.sources]
simple-module-hosting = { workspace = true }
simple-module-auth = { workspace = true }
simple-module-products = { workspace = true }
simple-module-dashboard = { workspace = true }
simple-module-datasets = { workspace = true }
simple-module-permissions = { workspace = true }
simple-module-background-tasks = { workspace = true }
simple-module-file-storage = { workspace = true }
simple-module-settings = { workspace = true }
simple-module-feature-flags = { workspace = true }
