// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// This file is replaced each time the host boots in development mode. The
// stub committed to git holds only the keys we need for type-checking when
// CI runs before the backend boots.

export default {
  translation: {} as Record<string, string>,
} as const;
