import {
  Activity,
  AlertCircle,
  Archive,
  BarChart3,
  Bell,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Clock,
  Cloud,
  Code,
  Cog,
  Copy,
  Cpu,
  CreditCard,
  Database,
  Download,
  Edit,
  Eye,
  EyeOff,
  File,
  Files,
  FileText,
  Filter,
  Flag,
  Folder,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Layers,
  Layout,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  Map as MapIcon,
  Menu,
  MessageSquare,
  Package,
  Palette,
  Pencil,
  Plus,
  RefreshCw,
  Save,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  Terminal,
  Trash,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react';

const ICON_MAP = {
  activity: Activity,
  'alert-circle': AlertCircle,
  archive: Archive,
  'bar-chart-3': BarChart3,
  bell: Bell,
  bookmark: Bookmark,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  copy: Copy,
  cpu: Cpu,
  'credit-card': CreditCard,
  database: Database,
  download: Download,
  edit: Edit,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  files: Files,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  layout: Layout,
  link: Link,
  list: List,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  map: MapIcon,
  menu: Menu,
  'message-square': MessageSquare,
  package: Package,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  'refresh-cw': RefreshCw,
  save: Save,
  'scroll-text': ScrollText,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  tag: Tag,
  terminal: Terminal,
  trash: Trash,
  upload: Upload,
  user: User,
  users: Users,
  x: X,
  zap: Zap,
} as const;

export type NavIconName = keyof typeof ICON_MAP;

/**
 * `className` replaces the default box so a caller can hide the icon at a
 * breakpoint — the phone drawer drops icons entirely, and a row that reserved
 * their space would keep the indent without the glyph.
 */
export function NavIcon({ name, className = 'w-5 h-5' }: { name: string; className?: string }) {
  if (!(name in ICON_MAP)) {
    return <span aria-hidden="true" className={className} />;
  }
  const Icon = ICON_MAP[name as NavIconName];
  return <Icon aria-hidden="true" className={className} strokeWidth={1.5} />;
}
