"""keycloak initial schema

Revision ID: 168a2882f443
Revises: 873ca2015033
Create Date: 2026-05-28 19:44:07.782353
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "168a2882f443"
down_revision: str | None = "873ca2015033"
branch_labels: str | Sequence[str] | None = ("keycloak",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keycloak_user_cache",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("keycloak_sub", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keycloak_user_cache")),
    )
    op.create_index(
        op.f("ix_keycloak_user_cache_keycloak_sub"),
        "keycloak_user_cache",
        ["keycloak_sub"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_keycloak_user_cache_keycloak_sub"), table_name="keycloak_user_cache")
    op.drop_table("keycloak_user_cache")
    # ### end Alembic commands ###
