"""initial schema

Revision ID: 2fdcd367b517
Revises: 53819c12d603
Create Date: 2026-04-15 12:06:38.726433
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2fdcd367b517'
down_revision: str | None = '53819c12d603'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_product', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products_product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products_product', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products_product', 'deleted_by')
    op.drop_column('products_product', 'deleted_at')
    op.drop_column('products_product', 'is_deleted')
    # ### end Alembic commands ###
