"""users oauth_account

Revision ID: 3bf3f9db7f7f
Revises: 77162e7b184b
Create Date: 2026-05-06 18:42:33.343257
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bf3f9db7f7f"
down_revision: str | None = "77162e7b184b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_oauth_account",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("oauth_name", sa.String(length=100), nullable=False),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=True),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("account_id", sa.String(length=320), nullable=False),
        sa.Column("account_email", sa.String(length=320), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
            name=op.f("fk_users_oauth_account_user_id_users_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_oauth_account")),
    )
    op.create_index(
        op.f("ix_users_oauth_account_account_id"),
        "users_oauth_account",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_oauth_account_oauth_name"),
        "users_oauth_account",
        ["oauth_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_oauth_account_user_id"), "users_oauth_account", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_oauth_account_user_id"), table_name="users_oauth_account")
    op.drop_index(op.f("ix_users_oauth_account_oauth_name"), table_name="users_oauth_account")
    op.drop_index(op.f("ix_users_oauth_account_account_id"), table_name="users_oauth_account")
    op.drop_table("users_oauth_account")
    # ### end Alembic commands ###
