"""add background_tasks_task_execution

Revision ID: 6df7645cc4d2
Revises: b7e1af4c9d02
Create Date: 2026-04-19 07:44:06.824688
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6df7645cc4d2"
down_revision: str | None = "b7e1af4c9d02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_tasks_task_execution",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("queue", sa.String(length=64), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("traceback", sa.String(), nullable=True),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("worker", sa.String(length=255), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("retried_from_id", sa.Uuid(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retried_from_id"],
            ["background_tasks_task_execution.id"],
            name=op.f(
                "fk_background_tasks_task_execution_retried_from_id_background_tasks_task_execution"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_tasks_task_execution")),
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_celery_task_id"),
        "background_tasks_task_execution",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_retried_from_id"),
        "background_tasks_task_execution",
        ["retried_from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_status"),
        "background_tasks_task_execution",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_background_tasks_task_execution_status_queued",
        "background_tasks_task_execution",
        ["status", "queued_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_task_name"),
        "background_tasks_task_execution",
        ["task_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_background_tasks_task_execution_task_name"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        "ix_background_tasks_task_execution_status_queued",
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_status"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_retried_from_id"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_celery_task_id"),
        table_name="background_tasks_task_execution",
    )
    op.drop_table("background_tasks_task_execution")
    # ### end Alembic commands ###
