"""add audit_log tables

Revision ID: 70786227af4c
Revises: 41cf2c53660e
Create Date: 2026-05-27 22:56:05.494513
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70786227af4c"
down_revision: str | None = "41cf2c53660e"
branch_labels: str | Sequence[str] | None = ("audit_log",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log_audit_entry",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("correlation_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log_audit_entry")),
    )
    op.create_index(
        "ix_audit_entry_created_at", "audit_log_audit_entry", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_entry_entity_id", "audit_log_audit_entry", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_audit_entry_entity_type", "audit_log_audit_entry", ["entity_type"], unique=False
    )
    op.create_index("ix_audit_entry_user_id", "audit_log_audit_entry", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_entry_user_id", table_name="audit_log_audit_entry")
    op.drop_index("ix_audit_entry_entity_type", table_name="audit_log_audit_entry")
    op.drop_index("ix_audit_entry_entity_id", table_name="audit_log_audit_entry")
    op.drop_index("ix_audit_entry_created_at", table_name="audit_log_audit_entry")
    op.drop_table("audit_log_audit_entry")
    # ### end Alembic commands ###
