"""initial schema

Revision ID: 77162e7b184b
Revises:
Create Date: 2026-04-30 23:59:42.399469
"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77162e7b184b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_tasks_task_execution",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("queue", sa.String(length=64), nullable=False),
        sa.Column("args", sa.JSON(), nullable=True),
        sa.Column("kwargs", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("traceback", sa.String(), nullable=True),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("worker", sa.String(length=255), nullable=True),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("retried_from_id", sa.Uuid(), nullable=True),
        sa.Column("queued_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retried_from_id"],
            ["background_tasks_task_execution.id"],
            name=op.f(
                "fk_background_tasks_task_execution_retried_from_id_background_tasks_task_execution"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_tasks_task_execution")),
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_celery_task_id"),
        "background_tasks_task_execution",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_retried_from_id"),
        "background_tasks_task_execution",
        ["retried_from_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_status"),
        "background_tasks_task_execution",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_background_tasks_task_execution_status_queued",
        "background_tasks_task_execution",
        ["status", "queued_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_background_tasks_task_execution_task_name"),
        "background_tasks_task_execution",
        ["task_name"],
        unique=False,
    )
    op.create_table(
        "feature_flags_override",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("scope_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags_override")),
        sa.UniqueConstraint(
            "scope", "scope_id", "name", name="uq_feature_flags_override_scope_scope_id_name"
        ),
    )
    op.create_index(
        op.f("ix_feature_flags_override_name"), "feature_flags_override", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_feature_flags_override_scope"), "feature_flags_override", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_feature_flags_override_scope_id"),
        "feature_flags_override",
        ["scope_id"],
        unique=False,
    )
    op.create_table(
        "file_storage_stored_file",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(length=32), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_storage_stored_file")),
    )
    op.create_index(
        "ix_file_storage_stored_file_created_by",
        "file_storage_stored_file",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "ix_file_storage_stored_file_is_deleted",
        "file_storage_stored_file",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        "ix_file_storage_stored_file_key", "file_storage_stored_file", ["key"], unique=True
    )
    op.create_table(
        "permissions_role_permission",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("role_name", sa.String(length=64), nullable=False),
        sa.Column("permission_key", sa.String(length=128), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint(
            "role_name", "permission_key", name=op.f("pk_permissions_role_permission")
        ),
    )
    op.create_index(
        "ix_permissions_role_permission_key",
        "permissions_role_permission",
        ["permission_key"],
        unique=False,
    )
    op.create_table(
        "permissions_user_permission",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("permission_key", sa.String(length=128), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_key", name=op.f("pk_permissions_user_permission")
        ),
    )
    op.create_index(
        "ix_permissions_user_permission_key",
        "permissions_user_permission",
        ["permission_key"],
        unique=False,
    )
    op.create_table(
        "settings_setting",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=10), nullable=False),
        sa.Column("scope_id", sa.String(length=255), nullable=False),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.String(length=4000), nullable=False),
        sa.Column("value_type", sa.String(length=10), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_setting")),
        sa.UniqueConstraint(
            "scope", "scope_id", "key", name="uq_settings_setting_scope_scope_id_key"
        ),
    )
    op.create_index(op.f("ix_settings_setting_key"), "settings_setting", ["key"], unique=False)
    op.create_index(op.f("ix_settings_setting_scope"), "settings_setting", ["scope"], unique=False)
    op.create_index(
        op.f("ix_settings_setting_scope_id"), "settings_setting", ["scope_id"], unique=False
    )
    op.create_table(
        "users_role",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_role")),
    )
    op.create_index(op.f("ix_users_role_name"), "users_role", ["name"], unique=True)
    op.create_table(
        "users_user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("tenant_id", sa.String(length=50), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_user")),
    )
    op.create_index(op.f("ix_users_user_email"), "users_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_user_last_login_at"), "users_user", ["last_login_at"], unique=False
    )
    op.create_index(op.f("ix_users_user_tenant_id"), "users_user", ["tenant_id"], unique=False)
    op.create_table(
        "users_access_token",
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
            name=op.f("fk_users_access_token_user_id_users_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_users_access_token")),
    )
    op.create_index(
        op.f("ix_users_access_token_created_at"), "users_access_token", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_users_access_token_user_id"), "users_access_token", ["user_id"], unique=False
    )
    op.create_table(
        "users_user_role",
        sa.Column("user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("role_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("assigned_by", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["users_role.id"],
            name=op.f("fk_users_user_role_role_id_users_role"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_user.id"],
            name=op.f("fk_users_user_role_user_id_users_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_users_user_role")),
    )
    op.create_index("ix_users_user_role_role_id", "users_user_role", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_user_role_role_id", table_name="users_user_role")
    op.drop_table("users_user_role")
    op.drop_index(op.f("ix_users_access_token_user_id"), table_name="users_access_token")
    op.drop_index(op.f("ix_users_access_token_created_at"), table_name="users_access_token")
    op.drop_table("users_access_token")
    op.drop_index(op.f("ix_users_user_tenant_id"), table_name="users_user")
    op.drop_index(op.f("ix_users_user_last_login_at"), table_name="users_user")
    op.drop_index(op.f("ix_users_user_email"), table_name="users_user")
    op.drop_table("users_user")
    op.drop_index(op.f("ix_users_role_name"), table_name="users_role")
    op.drop_table("users_role")
    op.drop_index(op.f("ix_settings_setting_scope_id"), table_name="settings_setting")
    op.drop_index(op.f("ix_settings_setting_scope"), table_name="settings_setting")
    op.drop_index(op.f("ix_settings_setting_key"), table_name="settings_setting")
    op.drop_table("settings_setting")
    op.drop_index("ix_permissions_user_permission_key", table_name="permissions_user_permission")
    op.drop_table("permissions_user_permission")
    op.drop_index("ix_permissions_role_permission_key", table_name="permissions_role_permission")
    op.drop_table("permissions_role_permission")
    op.drop_index("ix_file_storage_stored_file_key", table_name="file_storage_stored_file")
    op.drop_index("ix_file_storage_stored_file_is_deleted", table_name="file_storage_stored_file")
    op.drop_index("ix_file_storage_stored_file_created_by", table_name="file_storage_stored_file")
    op.drop_table("file_storage_stored_file")
    op.drop_index(op.f("ix_feature_flags_override_scope_id"), table_name="feature_flags_override")
    op.drop_index(op.f("ix_feature_flags_override_scope"), table_name="feature_flags_override")
    op.drop_index(op.f("ix_feature_flags_override_name"), table_name="feature_flags_override")
    op.drop_table("feature_flags_override")
    op.drop_index(
        op.f("ix_background_tasks_task_execution_task_name"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        "ix_background_tasks_task_execution_status_queued",
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_status"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_retried_from_id"),
        table_name="background_tasks_task_execution",
    )
    op.drop_index(
        op.f("ix_background_tasks_task_execution_celery_task_id"),
        table_name="background_tasks_task_execution",
    )
    op.drop_table("background_tasks_task_execution")
    # ### end Alembic commands ###
