"""users refresh_token table

Revision ID: 873ca2015033
Revises: 41cf2c53660e
Create Date: 2026-05-28 19:43:48.671727
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "873ca2015033"
down_revision: str | None = "41cf2c53660e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_refresh_token",
        sa.Column("token", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users_user.id"], name=op.f("fk_users_refresh_token_user_id_users_user")
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_users_refresh_token")),
    )
    op.create_index(
        op.f("ix_users_refresh_token_user_id"), "users_refresh_token", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_refresh_token_user_id"), table_name="users_refresh_token")
    op.drop_table("users_refresh_token")
    # ### end Alembic commands ###
