"""add indexes for dashboard queries

Revision ID: a01185374312
Revises: e3ce9754e6dc
Create Date: 2026-04-15 23:53:08.569085
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a01185374312"
down_revision: str | None = "e3ce9754e6dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_products_product_is_active"), "products_product", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_users_user_last_login_at"), "users_user", ["last_login_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_last_login_at"), table_name="users_user")
    op.drop_index(op.f("ix_products_product_is_active"), table_name="products_product")
    # ### end Alembic commands ###
