"""catalog initial

Revision ID: d46470b51f99
Revises: 92965b00f105
Create Date: 2026-08-02 17:21:01.065359
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d46470b51f99"
down_revision: str | None = "92965b00f105"
branch_labels: str | Sequence[str] | None = ("catalog",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_category",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_category")),
    )
    op.create_index(op.f("ix_catalog_category_slug"), "catalog_category", ["slug"], unique=True)
    op.create_table(
        "catalog_product",
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column("updated_by", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalog_category.id"],
            name=op.f("fk_catalog_product_category_id_catalog_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_product")),
    )
    op.create_index(
        "ix_catalog_product_category_id", "catalog_product", ["category_id"], unique=False
    )
    op.create_index("ix_catalog_product_name", "catalog_product", ["name"], unique=False)
    op.create_index(op.f("ix_catalog_product_sku"), "catalog_product", ["sku"], unique=True)
    op.create_index(
        "ix_catalog_product_status_created_at",
        "catalog_product",
        ["status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_catalog_product_status_created_at", table_name="catalog_product")
    op.drop_index(op.f("ix_catalog_product_sku"), table_name="catalog_product")
    op.drop_index("ix_catalog_product_name", table_name="catalog_product")
    op.drop_index("ix_catalog_product_category_id", table_name="catalog_product")
    op.drop_table("catalog_product")
    op.drop_index(op.f("ix_catalog_category_slug"), table_name="catalog_category")
    op.drop_table("catalog_category")
    # ### end Alembic commands ###
