"""Tests verifying the content and validity of files generated by scaffold_module."""

from __future__ import annotations

import ast
import tomllib
from pathlib import Path

import pytest
from new_module import scaffold_module


class TestGeneratedFilesSyntaxValidity:
    """Ensure every generated Python file is syntactically valid and TOML is parseable."""

    def test_all_python_files_parse(self, scaffolded_orders: Path):
        py_files = list(scaffolded_orders.parent.rglob("*.py"))
        assert len(py_files) > 0

        for py_file in py_files:
            try:
                ast.parse(py_file.read_text(), filename=str(py_file))
            except SyntaxError as e:
                pytest.fail(f"Generated file {py_file.name} has syntax error: {e}")

    def test_pyproject_toml_parses(self, scaffolded_orders: Path):
        data = tomllib.loads((scaffolded_orders.parent / "pyproject.toml").read_text())

        assert data["project"]["name"] == "orders"
        assert (
            data["project"]["entry-points"]["simple_module"]["orders"]
            == "orders.module:OrdersModule"
        )

    def test_compound_name_pyproject_toml_parses(self, module_root: Path):
        scaffold_module("blog_posts")

        pyproject = module_root / "modules" / "blog_posts" / "pyproject.toml"
        data = tomllib.loads(pyproject.read_text())

        assert data["project"]["name"] == "blog-posts"
        ep = data["project"]["entry-points"]["simple_module"]
        assert ep["blog_posts"] == "blog_posts.module:BlogPostsModule"


class TestGeneratedTemplateContent:
    """Verify key fragments of generated templates."""

    def test_service_has_full_crud(self, scaffolded_orders: Path):
        service = (scaffolded_orders / "service.py").read_text()
        assert "class OrderService:" in service
        assert "async def get_all(self)" in service
        assert "async def get_by_id(self" in service
        assert "async def create(self" in service
        assert "async def update(" in service
        assert "async def delete(self" in service

    def test_api_has_full_crud_endpoints(self, scaffolded_orders: Path):
        api = (scaffolded_orders / "endpoints" / "api.py").read_text()
        assert '@router.get("/"' in api
        assert '@router.get("/{order_id}"' in api
        assert '@router.post("/"' in api
        assert '@router.put("/{order_id}"' in api
        assert '@router.delete("/{order_id}"' in api
        assert "status_code=201" in api
        assert "status_code=204" in api

    def test_views_use_inertia(self, scaffolded_orders: Path):
        views = (scaffolded_orders / "endpoints" / "views.py").read_text()
        assert "InertiaResponse" in views
        assert "InertiaDep" in views
        assert '"Orders/Browse"' in views
        assert '"Orders/Create"' in views
        assert '"Orders/Edit"' in views

    def test_deps_provides_di_function(self, scaffolded_orders: Path):
        deps = (scaffolded_orders / "deps.py").read_text()
        assert "async def get_order_service(" in deps
        assert "Depends(get_db)" in deps

    def test_contracts_protocol_defined(self, scaffolded_orders: Path):
        protocol = (scaffolded_orders / "contracts" / "service.py").read_text()
        assert "class IOrderService(Protocol):" in protocol

    def test_contracts_init_exports_public_api(self, scaffolded_orders: Path):
        init = (scaffolded_orders / "contracts" / "__init__.py").read_text()
        assert '"OrderCreate"' in init
        assert '"OrderOut"' in init
        assert '"OrderUpdate"' in init
        assert '"IOrderService"' in init

    def test_module_class_registers_routes(self, scaffolded_orders: Path):
        module_py = (scaffolded_orders / "module.py").read_text()
        assert "def register_routes(" in module_py
        assert "api_router.include_router(api)" in module_py
        assert "view_router.include_router(views)" in module_py

    def test_module_class_registers_permissions(self, scaffolded_orders: Path):
        module_py = (scaffolded_orders / "module.py").read_text()
        assert '"orders.view"' in module_py
        assert '"orders.create"' in module_py
        assert '"orders.edit"' in module_py
        assert '"orders.delete"' in module_py

    def test_model_has_audit_mixin(self, scaffolded_orders: Path):
        model = (scaffolded_orders / "models.py").read_text()
        assert "from simple_module_db.mixins import AuditMixin" in model
        assert "class Order(Base, AuditMixin, table=True):" in model
        assert '__tablename__ = "orders_order"' in model

    def test_test_file_has_test_classes(self, scaffolded_orders: Path):
        test_file = (scaffolded_orders.parent / "tests" / "test_orders.py").read_text()
        assert "class TestOrderSchemas:" in test_file
        assert "class TestOrderService:" in test_file
        assert "class TestOrdersAPI:" in test_file
        assert "class TestOrdersModuleLifecycle:" in test_file

    def test_module_py_registers_locale_dirs(self, scaffolded_orders: Path):
        """Scaffolded module.py must expose locale_dirs() pointing at locales/."""
        module_py = (scaffolded_orders / "module.py").read_text()
        assert "import importlib.resources" in module_py
        assert "def locale_dirs(self)" in module_py
        assert '"orders"' in module_py
        assert '"locales"' in module_py

    def test_locales_en_json_exists_and_parses(self, scaffolded_orders: Path):
        """Scaffolded modules ship a starter en.json with valid JSON."""
        import json

        locale_file = scaffolded_orders / "locales" / "en.json"
        assert locale_file.exists()
        data = json.loads(locale_file.read_text())
        # Keys must match what the scaffolded pages call t() with.
        assert data["browse"]["title"] == "Orders"
        assert data["browse"]["new_button"] == "New Order"
        assert data["create"]["submit_button"] == "Create"
        assert data["edit"]["submit_button"] == "Save"
        assert "name_label" in data["form"]
        assert "description_label" in data["form"]

    def test_pages_use_use_t_hook(self, scaffolded_orders: Path):
        """Scaffolded Browse/Create/Edit pages must import keys + useT and use typed keys."""
        for page in ("Browse.tsx", "Create.tsx", "Edit.tsx"):
            content = (scaffolded_orders / "pages" / page).read_text()
            assert "from '@simple-module/i18n'" in content, f"{page} missing i18n import"
            assert "keys" in content and "useT" in content, f"{page} missing keys/useT import"
            assert "const { t } = useT();" in content, f"{page} does not call useT()"
            # Typed-key calls use property access, not string literals.
            assert "t(keys.orders." in content, f"{page} does not invoke t(keys.orders.*)"
            assert "t('orders." not in content, f"{page} still uses string-literal t('orders.*')"
