"""Per-module frontend asset discovery and CSS emission.

Split out from :mod:`simple_module_hosting.manifest`, which is already at the
repo's 300-line cap. ``manifest.py`` imports from here.

A module may ship two optional stylesheets beside its ``pages/`` directory:

* ``theme.css`` — ``@theme`` tokens, ``@custom-variant``, ``@font-face``.
  Imported *unlayered*, because a ``@theme`` block inside a cascade layer is
  inert and registers no design tokens.
* ``styles.css`` — component rules, keyframes, vendor CSS. Imported into
  ``layer(components)``, because unlayered CSS outranks every Tailwind
  utility: a module shipping a bare ``.card { padding: 0 }`` would otherwise
  silently beat ``p-4``.

Both are referenced by **absolute** filesystem path, exactly as the ``@source``
lines in the same file already are.

This used to emit a per-module Vite alias (``#module/<pkg>/styles.css``) to
avoid a relative path like ``../../../.venv/lib/python3.12/site-packages/<pkg>``
— but that objection only ever applied to *relative* paths, and the alias made
this generated file depend on the host resolving it. ``vite.config.ts`` is
scaffold output: it is written once into an app and then owned and edited
there, so it is versioned independently of these Python packages. A host
scaffolded before the alias existed never receives it, and a Python-only
dependency bump would emit specifiers that host cannot resolve, failing the
build with ``Can't resolve '#module/<pkg>/styles.css'`` — naming something that
appears nowhere in the app's own sources (GH issue #253).

Absolute paths keep the generated CSS self-contained: it resolves under any
``vite.config.ts``, old or new, with no alias configured at all.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

from simple_module_core import ModuleBase, get_module_package_name

logger = logging.getLogger(__name__)

THEME_CSS = "theme.css"
STYLES_CSS = "styles.css"


@dataclass(frozen=True)
class ModuleAssets:
    """Frontend assets a single module contributes."""

    name: str
    package_name: str
    package_dir: Path
    pages_dir: Path | None
    theme_css: Path | None
    styles_css: Path | None


def compute_module_assets(modules: Sequence[ModuleBase]) -> list[ModuleAssets]:
    """Return per-module frontend assets, preserving discovery order.

    Discovery order matters. ``discover_modules()`` topologically sorts by
    ``ModuleMeta.depends_on``, which is the order the host invokes
    ``register_*`` hooks in; emitting CSS in that same order means a module
    that depends on another can override its dependency's styles.

    A module is included only if it contributes at least one asset.
    """
    result: list[ModuleAssets] = []
    for mod in modules:
        pkg_name = get_module_package_name(mod)
        try:
            pkg_root = Path(str(importlib.resources.files(pkg_name)))
        except (ModuleNotFoundError, TypeError):
            logger.debug(
                "Module '%s': package %s not importable — skipping", mod.meta.name, pkg_name
            )
            continue
        pages_dir = pkg_root / "pages"
        theme = pkg_root / THEME_CSS
        styles = pkg_root / STYLES_CSS
        entry = ModuleAssets(
            name=mod.meta.name,
            package_name=pkg_name,
            package_dir=pkg_root.resolve(),
            pages_dir=pages_dir.resolve() if pages_dir.is_dir() else None,
            theme_css=theme.resolve() if theme.is_file() else None,
            styles_css=styles.resolve() if styles.is_file() else None,
        )
        if entry.pages_dir or entry.theme_css or entry.styles_css:
            result.append(entry)
    return result


_CSS_HEADER = """\
/* AUTO-GENERATED by simple_module_hosting.assets — do not edit by hand.
 * Regenerate with: smpy gen-pages
 *
 * Emission order is module discovery order (topological by depends_on), so a
 * dependent module's CSS can override its dependency's.
 *
 * theme.css is imported unlayered so its @theme blocks register as design
 * tokens; styles.css is imported into layer(components) so a module rule can
 * never outrank a Tailwind utility.
 */"""


def render_modules_css(
    assets: Sequence[ModuleAssets],
    *,
    in_repo: Callable[[Path], bool],
) -> str:
    """Render the contents of ``modules.generated.css``.

    ``@source`` is emitted only for wheel-installed modules — in-repo module
    pages are already covered by the static ``@source`` glob in the host's
    ``styles.css``, so emitting an absolute one too would just duplicate it.
    ``@import`` is emitted for *every* module, in-repo and wheel alike, because
    there is no static-glob equivalent for CSS.

    Every path is absolute, so nothing here depends on the host's
    ``vite.config.ts`` — see the module docstring for why that matters.
    """
    source_lines = [
        f'@source "{e.pages_dir.as_posix()}/**/*.{{ts,tsx}}";'
        for e in assets
        if e.pages_dir and not in_repo(e.pages_dir)
    ]
    theme_lines = [f'@import "{e.theme_css.as_posix()}";' for e in assets if e.theme_css]
    style_lines = [
        f'@import "{e.styles_css.as_posix()}" layer(components);' for e in assets if e.styles_css
    ]

    out = [_CSS_HEADER]
    for heading, lines in (
        ("/* ── @source: class scanning (wheel-installed modules) ── */", source_lines),
        ("/* ── theme: unlayered, registers @theme tokens ── */", theme_lines),
        ("/* ── styles: layer(components), always loses to utilities ── */", style_lines),
    ):
        if lines:
            out.append("")
            out.append(heading)
            out.extend(lines)
    out.append("")
    return "\n".join(out)


def render_assets_json(assets: Sequence[ModuleAssets]) -> str:
    """Render ``modules.assets.json`` — the richer companion to the pages manifest.

    Kept separate from ``modules.manifest.json`` rather than replacing it:
    ``vite.config.ts`` is scaffolded *into* each app, so changing the existing
    manifest's value shape would break every downstream app at once. This file
    is purely additive, and also covers CSS-only modules that never appear in
    the pages manifest because they ship no ``pages/``.
    """
    payload = {
        e.name: {
            "package_name": e.package_name,
            "package": e.package_dir.as_posix(),
            "pages": e.pages_dir.as_posix() if e.pages_dir else None,
            "theme": e.theme_css.as_posix() if e.theme_css else None,
            "styles": e.styles_css.as_posix() if e.styles_css else None,
        }
        for e in assets
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"
