"""Emit generated-resources.ts + keys.generated.ts for the frontend.

Both files are consumed by ``@simple-module/i18n``:

* ``generated-resources.ts`` — flat empty-string keys, fed into i18next's
  ``CustomTypeOptions['resources']`` so ``t('foo.bar')`` narrows to the
  accepted key union.

* ``keys.generated.ts`` — a nested ``keys`` constant whose leaves are the
  full dotted key strings. Consumers use ``t(keys.foo.bar)`` instead of
  string literals, so typos become property-access errors at the call
  site and IDE autocomplete works at every dot.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from simple_module_core.i18n import I18nRegistry

logger = logging.getLogger(__name__)

_RESOURCES_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.
//
// Shape of the default locale's keys. Values are empty strings; only the
// key set is consumed by TypeScript via the i18next module augmentation
// in packages/i18n/src/types.ts.
"""

_KEYS_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.
//
// Nested constant tree of translation keys. Import from
// '@simple-module/i18n' and use like:
//
//   import { keys } from '@simple-module/i18n';
//   t(keys.products.browse.title);
//
// Each leaf is the full dotted key string. Typos are caught at
// property-access time, not inside t().
"""

# CLDR plural suffixes that i18next appends via the `count` param. When any
# `<stem>_<suffix>` exists we also emit a virtual `<stem>` leaf so callers
# can write `t(keys.foo.items, { count })` — i18next's runtime plural
# resolution adds the suffix automatically.
_PLURAL_SUFFIXES = ("_zero", "_one", "_two", "_few", "_many", "_other")


def write_generated_resources(registry: I18nRegistry, output_dir: Path) -> Path:
    """Write both ``generated-resources.ts`` and ``keys.generated.ts``.

    Returns the path of the resources file (the keys file is emitted beside it).
    Both files are written only when their content differs from disk.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    default_locale = registry.default_locale
    messages = registry.messages(default_locale)
    keys = sorted(messages.keys())

    resources_path = output_dir / "generated-resources.ts"
    _write_if_changed(resources_path, _render_resources(keys))

    keys_path = output_dir / "keys.generated.ts"
    _write_if_changed(keys_path, _render_keys(keys))

    return resources_path


def _render_resources(keys: list[str]) -> str:
    lines = [_RESOURCES_HEADER, "", "export default {", "  translation: {"]
    for key in keys:
        lines.append(f"    '{key}': '',")
    lines.append("  },")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def _render_keys(keys: list[str]) -> str:
    """Render the nested ``keys`` constant tree."""
    tree = _build_key_tree(keys)
    lines = [_KEYS_HEADER, "", "export const keys = "]
    lines.append(_serialize(tree, indent=0) + " as const;")
    lines.append("")
    return "\n".join(lines)


def _build_key_tree(flat_keys: list[str]) -> dict[str, Any]:
    """Build a nested dict from a list of dotted keys.

    Leaves are the full dotted key string. Plural stems (e.g. ``foo.items``
    when ``foo.items_one``/``foo.items_other`` exist) are added as virtual
    leaves so callers can pass them directly to ``t(key, {count})``.
    """
    tree: dict[str, Any] = {}
    stems: set[str] = set()

    for flat_key in flat_keys:
        # Collect plural stems.
        for suffix in _PLURAL_SUFFIXES:
            if flat_key.endswith(suffix):
                stems.add(flat_key[: -len(suffix)])
                break
        _insert(tree, flat_key.split("."), flat_key)

    # Inject virtual stems that aren't already concrete keys.
    existing = set(flat_keys)
    for stem in sorted(stems):
        if stem in existing:
            continue
        _insert(tree, stem.split("."), stem)

    return tree


def _insert(tree: dict[str, Any], path: list[str], value: str) -> None:
    """Insert ``value`` into ``tree`` at ``path``.

    If a path segment conflicts with an existing leaf (e.g. a plural stem
    coincides with a real key segment), the existing leaf wins — we do not
    overwrite real content with virtual stems. This keeps the invariant that
    real keys are always accurate.
    """
    cursor: Any = tree
    for segment in path[:-1]:
        existing = cursor.get(segment)
        if isinstance(existing, dict):
            cursor = existing
        elif existing is None:
            new_dict: dict[str, Any] = {}
            cursor[segment] = new_dict
            cursor = new_dict
        else:
            # Path collides with an existing leaf — abort insertion silently.
            # Leaf wins; stems cannot shadow real keys.
            return
    leaf_key = path[-1]
    if leaf_key not in cursor:
        cursor[leaf_key] = value


def _serialize(node: Any, *, indent: int) -> str:
    """Emit a dict-of-dicts tree as pretty-printed TypeScript object literal."""
    if isinstance(node, str):
        return json.dumps(node)
    if not isinstance(node, dict) or not node:
        return "{}"
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    lines = ["{"]
    for k in sorted(node.keys()):
        key_repr = k if _is_valid_js_identifier(k) else json.dumps(k)
        lines.append(f"{inner_pad}{key_repr}: {_serialize(node[k], indent=indent + 1)},")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def _is_valid_js_identifier(name: str) -> bool:
    """True if ``name`` can be an unquoted object key in JS (ASCII subset)."""
    if not name or not (name[0].isalpha() or name[0] in "_$"):
        return False
    return all(c.isalnum() or c in "_$" for c in name)


def _write_if_changed(target: Path, payload: str) -> None:
    try:
        existing = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    if existing != payload:
        target.write_text(payload, encoding="utf-8")
        logger.info("Wrote %s", target.name)
