"""Emit generated-resources.ts for frontend TypeScript type augmentation."""

from __future__ import annotations

import logging
from pathlib import Path

from simple_module_core.i18n import I18nRegistry

logger = logging.getLogger(__name__)

_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.
//
// Shape of the default locale's keys. Values are empty strings; only the
// key set is consumed by TypeScript via i18n-types.ts module augmentation.
"""


def write_generated_resources(registry: I18nRegistry, output_dir: Path) -> Path:
    """Write ``generated-resources.ts`` into ``output_dir``.

    Emits the default-locale key shape with empty string values, so i18next's
    ``CustomTypeOptions['resources']`` augmentation infers the available keys.
    Writes only when content differs from what's on disk.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    target = output_dir / "generated-resources.ts"

    default_locale = registry.default_locale
    messages = registry.messages(default_locale)
    keys = sorted(messages.keys())

    lines = [_HEADER, "", "export default {", "  translation: {"]
    for key in keys:
        # Single-quote key, empty-string value, trailing comma for diff-friendliness.
        lines.append(f"    '{key}': '',")
    lines.append("  },")
    lines.append("} as const;")
    lines.append("")
    payload = "\n".join(lines)

    try:
        existing = target.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None

    if existing != payload:
        target.write_text(payload, encoding="utf-8")
        logger.info("Wrote %s (%d keys)", target.name, len(keys))

    return target
