"""Emit generated-resources.ts + keys.generated.ts for the frontend.

Both files are consumed by ``@simple-module/i18n``:

* ``generated-resources.ts`` — flat empty-string keys, fed into i18next's
  ``CustomTypeOptions['resources']`` so ``t('foo.bar')`` narrows to the
  accepted key union.

* ``keys.generated.ts`` — a nested ``keys`` constant whose leaves are the
  full dotted key strings. Consumers use ``t(keys.foo.bar)`` for typed
  call-sites.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from simple_module_core import ModuleBase
from simple_module_core.i18n import PLURAL_CATEGORIES, I18nRegistry

from simple_module_hosting.manifest import _write_if_changed
from simple_module_hosting.settings import Settings

logger = logging.getLogger(__name__)


def build_i18n_registry(
    settings: Settings,
    modules: list[ModuleBase],
    project_root: Path,
) -> tuple[I18nRegistry, list[tuple[str, str, Path]]]:
    """Construct the i18n registry from module + host + UI sources.

    Returns ``(registry, extra_sources)`` where ``extra_sources`` is the list
    of ``(reporter_name, namespace, dir)`` triples the diagnostic runner
    needs to validate non-module locale directories.
    """
    registry = I18nRegistry(
        default_locale=settings.i18n_default_locale,
        supported_locales=settings.i18n_supported_locales,
    )
    extra_sources: list[tuple[str, str, Path]] = []

    for mod in modules:
        for namespace, locale_dir in mod.locale_dirs().items():
            registry.add_source(namespace, locale_dir)

    host_locales = project_root / "host" / "locales"
    if host_locales.is_dir():
        registry.add_source("host", host_locales)
        extra_sources.append(("host", "host", host_locales))

    ui_locales = project_root / "packages" / "ui" / "locales"
    if ui_locales.is_dir():
        registry.add_source("ui", ui_locales)
        extra_sources.append(("packages/ui", "ui", ui_locales))

    registry.load()
    return registry, extra_sources


def emit_frontend_types(registry: I18nRegistry, project_root: Path) -> None:
    """Write the TS augmentation files into @simple-module/i18n if present.

    Logs but does not raise on failure — stale types are preferable to a
    broken boot. Dev-loop only; callers should gate on ``is_development``.
    """
    try:
        pkg_src = project_root / "packages" / "i18n" / "src"
        if pkg_src.is_dir():
            write_generated_resources(registry, pkg_src)
    except Exception:
        logger.exception("Failed to write generated-resources.ts — frontend types will be stale")


_RESOURCES_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.
"""

_KEYS_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.
"""

_PLURAL_SUFFIXES: tuple[str, ...] = tuple(f"_{c}" for c in PLURAL_CATEGORIES)


def write_generated_resources(registry: I18nRegistry, output_dir: Path) -> Path:
    """Write both ``generated-resources.ts`` and ``keys.generated.ts``.

    Returns the path of the resources file. Both files skip the disk write
    when content matches what's already on disk (to avoid bumping mtimes
    that would trigger spurious Vite HMR).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    messages = registry.messages(registry.default_locale)
    keys = sorted(messages.keys())

    resources_path = output_dir / "generated-resources.ts"
    if _write_if_changed(resources_path, _render_resources(keys)):
        logger.info("Wrote %s (%d keys)", resources_path.name, len(keys))

    keys_path = output_dir / "keys.generated.ts"
    if _write_if_changed(keys_path, _render_keys(keys)):
        logger.info("Wrote %s", keys_path.name)

    return resources_path


def _render_resources(keys: list[str]) -> str:
    lines = [_RESOURCES_HEADER, "", "export default {", "  translation: {"]
    for key in keys:
        lines.append(f"    '{key}': '',")
    lines.append("  },")
    lines.append("} as const;")
    lines.append("")
    return "\n".join(lines)


def _render_keys(keys: list[str]) -> str:
    """Render the nested ``keys`` constant tree."""
    tree = _build_key_tree(keys)
    return f"{_KEYS_HEADER}\nexport const keys = {_serialize(tree, indent=0)} as const;\n"


def _build_key_tree(flat_keys: list[str]) -> dict[str, Any]:
    """Build a nested dict from a list of dotted keys.

    Leaves are the full dotted key string. Plural stems (e.g. ``foo.items``
    when ``foo.items_one``/``foo.items_other`` exist) are added as virtual
    leaves so callers can pass them directly to ``t(key, {count})``.
    """
    tree: dict[str, Any] = {}
    stems: set[str] = set()

    for flat_key in flat_keys:
        for suffix in _PLURAL_SUFFIXES:
            if flat_key.endswith(suffix):
                stems.add(flat_key[: -len(suffix)])
                break
        _insert(tree, flat_key.split("."), flat_key)

    existing = set(flat_keys)
    for stem in stems:
        if stem in existing:
            continue
        _insert(tree, stem.split("."), stem)

    return tree


def _insert(tree: dict[str, Any], path: list[str], value: str) -> None:
    """Insert ``value`` into ``tree`` at ``path``.

    Existing leaves win over later inserts — real keys cannot be shadowed
    by virtual plural stems, and a path segment that collides with an
    existing leaf causes the insertion to be silently aborted.
    """
    cursor: Any = tree
    for segment in path[:-1]:
        existing = cursor.get(segment)
        if isinstance(existing, dict):
            cursor = existing
        elif existing is None:
            new_dict: dict[str, Any] = {}
            cursor[segment] = new_dict
            cursor = new_dict
        else:
            return
    leaf_key = path[-1]
    if leaf_key not in cursor:
        cursor[leaf_key] = value


def _serialize(node: Any, *, indent: int) -> str:
    """Emit a dict-of-dicts tree as pretty-printed TypeScript object literal."""
    if isinstance(node, str):
        return json.dumps(node)
    if not isinstance(node, dict) or not node:
        return "{}"
    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    lines = ["{"]
    for k in sorted(node.keys()):
        key_repr = k if _is_valid_js_identifier(k) else json.dumps(k)
        lines.append(f"{inner_pad}{key_repr}: {_serialize(node[k], indent=indent + 1)},")
    lines.append(f"{pad}}}")
    return "\n".join(lines)


def _is_valid_js_identifier(name: str) -> bool:
    """True if ``name`` can be an unquoted object key in JS (ASCII subset)."""
    if not name or not (name[0].isalpha() or name[0] in "_$"):
        return False
    return all(c.isalnum() or c in "_$" for c in name)
