"""Frontend pages manifest + per-module JS dependency discovery.

* :func:`write_module_pages_manifest` emits the three generated files Vite
  and Tailwind read at build time:
  - ``modules.manifest.json`` — name -> absolute pages dir
  - ``modules.generated.ts`` — ``import.meta.glob`` per module
  - ``modules.generated.css`` — ``@source`` per wheel-installed module
* :func:`read_module_package_json` / :func:`collect_module_js_deps` locate
  the per-module ``package.json`` shipped inside wheels (or alongside the
  source for editable installs) and aggregate its ``dependencies`` block.
  Used by the ``sm sync-js-deps`` CLI.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
import os
from collections.abc import Sequence
from pathlib import Path

from simple_module_core import ModuleBase, get_module_package_name

logger = logging.getLogger(__name__)

_GENERATED_TS_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.manifest — do not edit by hand.
// Regenerate with: sm gen-pages
//
// Maps ModuleName -> record of page import paths. Paths below are
// relative to this file (host/client_app/) so that pages shipped inside
// pip-installed module wheels are picked up by Vite's import.meta.glob.
"""

_GENERATED_CSS_HEADER = """\
/* AUTO-GENERATED by simple_module_hosting.manifest — do not edit by hand.
 * Regenerate with: sm gen-pages
 *
 * @source entries for module pages shipped inside pip-installed wheels.
 * In-repo modules are covered by the static @source glob in
 * host/client_app/styles.css.
 */
"""


def repo_root_from_client_app(client_app_dir: Path) -> Path:
    """Repo root is two levels above ``host/client_app/``.

    Both ``write_module_pages_manifest`` and the ``sync-js-deps`` CLI
    derive the workspace root from the host's client_app directory.
    Centralized here so the heuristic lives in exactly one place.
    """
    return client_app_dir.resolve().parent.parent


def compute_module_pages(modules: Sequence[ModuleBase]) -> dict[str, Path]:
    """Return a ``{ModuleName: absolute pages/ Path}`` map for modules that ship TSX pages.

    A module is included only if ``<package>/pages/`` exists on disk.
    """
    result: dict[str, Path] = {}
    for mod in modules:
        pkg_name = get_module_package_name(mod)
        try:
            pkg_root = importlib.resources.files(pkg_name)
        except ModuleNotFoundError:
            logger.debug(
                "Module '%s': package %s not importable — skipping", mod.meta.name, pkg_name
            )
            continue
        pages_dir = Path(str(pkg_root)) / "pages"
        if not pages_dir.is_dir():
            logger.debug(
                "Module '%s' has no pages/ at %s — skipping frontend manifest entry",
                mod.meta.name,
                pages_dir,
            )
            continue
        result[mod.meta.name] = pages_dir.resolve()
    return result


def _write_if_changed(path: Path, payload: str) -> bool:
    """Write ``payload`` to ``path`` only if the on-disk content differs.

    Avoids bumping the file's mtime on every dev-server boot, which would
    otherwise cascade into Vite's file-watcher and trigger spurious HMR.
    Returns True if a write happened.
    """
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    if existing == payload:
        return False
    path.write_text(payload, encoding="utf-8")
    return True


def _is_in_repo_module(pages_dir: Path, repo_root: Path | None) -> bool:
    """True if ``pages_dir`` lives under the working tree's ``modules/`` dir.

    Those modules are already covered by the static ``@source`` glob in
    host/client_app/styles.css, so we shouldn't emit a duplicate absolute
    entry for them in the generated CSS.
    """
    if repo_root is None:
        return False
    try:
        rel = pages_dir.resolve().relative_to(repo_root.resolve())
    except ValueError:
        return False
    return len(rel.parts) >= 2 and rel.parts[0] == "modules"


def write_module_pages_manifest(
    modules: Sequence[ModuleBase],
    output_dir: Path,
    repo_root: Path | None = None,
) -> dict[str, Path]:
    """Write the three generated files (manifest JSON, glob TS, Tailwind CSS).

    Returns the paths that were written. Content is written only when
    different from what's on disk, so booting the host repeatedly in dev
    does not wake up Vite's file watcher.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if repo_root is None:
        repo_root = repo_root_from_client_app(output_dir)

    pages_map = compute_module_pages(modules)

    manifest_path = output_dir / "modules.manifest.json"
    manifest_payload = {name: path.as_posix() for name, path in pages_map.items()}
    manifest_text = json.dumps(manifest_payload, indent=2, sort_keys=True) + "\n"

    generated_path = output_dir / "modules.generated.ts"
    lines: list[str] = [
        _GENERATED_TS_HEADER,
        "",
        "import type { ComponentType } from 'react';",
        "",
        "type PageModule = { default: ComponentType<Record<string, unknown>> };",
        "",
        "export const moduleGlobs: Record<string, Record<string, () => Promise<PageModule>>> = {",
    ]
    for name in sorted(pages_map):
        lines.append(
            f"  {json.dumps(name)}: import.meta.glob<PageModule>"
            f"({json.dumps(_glob_pattern_for(pages_map[name], output_dir))}),"
        )
    lines.append("};")
    lines.append("")
    generated_text = "\n".join(lines)

    # In-repo modules are already covered by the static glob in styles.css;
    # only emit @source for wheel-installed ones. pages_map is keyed by
    # module name so each pages_dir is unique — no further dedup needed.
    css_path = output_dir / "modules.generated.css"
    css_lines: list[str] = [_GENERATED_CSS_HEADER]
    for name in sorted(pages_map):
        pages_dir = pages_map[name]
        if _is_in_repo_module(pages_dir, repo_root):
            continue
        css_lines.append(f'@source "{pages_dir.as_posix()}";')
    css_lines.append("")
    css_text = "\n".join(css_lines)

    wrote_manifest = _write_if_changed(manifest_path, manifest_text)
    wrote_generated = _write_if_changed(generated_path, generated_text)
    wrote_css = _write_if_changed(css_path, css_text)

    if wrote_manifest or wrote_generated or wrote_css:
        logger.info(
            "Wrote module pages manifest: %d module(s) -> %s, %s, %s",
            len(pages_map),
            manifest_path.name,
            generated_path.name,
            css_path.name,
        )
    return {"manifest": manifest_path, "generated": generated_path, "css": css_path}


def _glob_pattern_for(pages_dir: Path, output_dir: Path) -> str:
    """Build a Vite ``import.meta.glob`` pattern relative to ``output_dir``.

    Vite 8 interprets filesystem-absolute paths against the project root,
    not the filesystem, so we always emit the path relative to the file
    where the glob lives (``modules.generated.ts`` under ``output_dir``).
    """
    try:
        rel = Path(os.path.relpath(pages_dir, output_dir.resolve()))
    except ValueError:
        # Different drive on Windows — fall back to absolute (rare).
        return pages_dir.as_posix() + "/*.tsx"
    rel_str = rel.as_posix()
    if not rel_str.startswith(("./", "../")):
        rel_str = "./" + rel_str
    return rel_str + "/*.tsx"


def read_module_package_json(mod: ModuleBase) -> dict | None:
    """Return the parsed ``package.json`` for a module, or ``None`` if absent.

    Tries two locations so both install modes work:

    * ``<pkg>/package.json`` — force-included into the wheel by Hatch.
    * ``<pkg>/../package.json`` — the source-tree module root, used by
      editable installs and in-repo workspace members where the wheel
      hasn't been built yet.
    """
    pkg_name = get_module_package_name(mod)
    try:
        pkg_root = Path(str(importlib.resources.files(pkg_name)))
    except ModuleNotFoundError:
        return None
    for candidate in (pkg_root / "package.json", pkg_root.parent / "package.json"):
        if candidate.is_file():
            try:
                return json.loads(candidate.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                logger.warning(
                    "Module '%s' has an invalid package.json at %s: %s",
                    mod.meta.name,
                    candidate,
                    exc,
                )
                return None
    return None


def collect_module_js_deps(modules: Sequence[ModuleBase]) -> dict[str, dict[str, str]]:
    """Return ``{module_name: {dep: range}}`` for modules that declare deps.

    Reads only the ``dependencies`` block; ``peerDependencies`` are
    host-provided singletons and must not be installed from modules.
    Modules without a ``package.json`` or without a ``dependencies`` block
    are silently skipped.
    """
    out: dict[str, dict[str, str]] = {}
    for mod in modules:
        pkg = read_module_package_json(mod)
        if not pkg:
            continue
        deps = pkg.get("dependencies") or {}
        if deps:
            out[mod.meta.name] = {str(k): str(v) for k, v in deps.items()}
    return out
