"""Scaffolding helpers: frontend pages manifest, host scaffold, module scaffold.

Three responsibilities:

* :func:`write_module_pages_manifest` — emits
  ``modules.manifest.json`` and ``modules.generated.ts`` so Vite can find
  pages shipped inside pip-installed module wheels.
* :func:`create_host` — materializes a new host project from the
  package-data templates under ``simple_module_hosting/templates/host/``.
* :func:`create_module` — materializes a new module package from
  ``simple_module_hosting/templates/module/``.

The two ``create_*`` helpers share :func:`_apply_template_files`, which
handles the common work of walking a template tree, stripping ``.tpl``,
substituting placeholders, and copying vs. writing each file.
"""

from __future__ import annotations

import importlib.resources
import json
import logging
import re
import shutil
from collections.abc import Mapping, Sequence
from pathlib import Path

from simple_module_core import ModuleBase, get_module_package_name

logger = logging.getLogger(__name__)

# Templates ship as package data under simple_module_hosting/templates/{host,module}/.
_TEMPLATES_PACKAGE = "simple_module_hosting.templates"

_GENERATED_TS_HEADER = """\
// AUTO-GENERATED by simple_module_hosting.scaffolding — do not edit by hand.
// Regenerate with: sm gen-pages
//
// Maps ModuleName -> record of page import paths. The absolute paths below
// are resolved at build time so pages shipped inside pip-installed module
// wheels are picked up by Vite's import.meta.glob.
"""

# Path-segment substitution tokens used by create_module.
_PACKAGE_PATH_TOKEN = "__PACKAGE__"


# ── Frontend pages manifest ─────────────────────────────────────────


def compute_module_pages(modules: Sequence[ModuleBase]) -> dict[str, Path]:
    """Return a ``{ModuleName: absolute pages/ Path}`` map for modules that ship TSX pages.

    A module is included only if ``<package>/pages/`` exists on disk.
    """
    result: dict[str, Path] = {}
    for mod in modules:
        pkg_name = get_module_package_name(mod)
        try:
            pkg_root = importlib.resources.files(pkg_name)
        except ModuleNotFoundError:
            logger.debug(
                "Module '%s': package %s not importable — skipping", mod.meta.name, pkg_name
            )
            continue
        pages_dir = Path(str(pkg_root)) / "pages"
        if not pages_dir.is_dir():
            logger.debug(
                "Module '%s' has no pages/ at %s — skipping frontend manifest entry",
                mod.meta.name,
                pages_dir,
            )
            continue
        result[mod.meta.name] = pages_dir.resolve()
    return result


def _write_if_changed(path: Path, payload: str) -> bool:
    """Write ``payload`` to ``path`` only if the on-disk content differs.

    Avoids bumping the file's mtime on every dev-server boot, which would
    otherwise cascade into Vite's file-watcher and trigger spurious HMR.
    Returns True if a write happened.
    """
    try:
        existing = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        existing = None
    if existing == payload:
        return False
    path.write_text(payload, encoding="utf-8")
    return True


def write_module_pages_manifest(
    modules: Sequence[ModuleBase],
    output_dir: Path,
) -> dict[str, Path]:
    """Write ``modules.manifest.json`` and ``modules.generated.ts`` into ``output_dir``.

    Returns the paths of the two files that were written. Content is written
    only when different from what's already on disk, so booting the host
    repeatedly in dev does not wake up Vite's file watcher.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pages_map = compute_module_pages(modules)

    manifest_path = output_dir / "modules.manifest.json"
    manifest_payload = {name: str(path).replace("\\", "/") for name, path in pages_map.items()}
    manifest_text = json.dumps(manifest_payload, indent=2, sort_keys=True) + "\n"

    generated_path = output_dir / "modules.generated.ts"
    lines: list[str] = [
        _GENERATED_TS_HEADER,
        "",
        "import type { ComponentType } from 'react';",
        "",
        "type PageModule = { default: ComponentType<Record<string, unknown>> };",
        "",
        "export const moduleGlobs: Record<string, Record<string, () => Promise<PageModule>>> = {",
    ]
    for name in sorted(pages_map):
        # Vite's import.meta.glob requires a string literal at build time;
        # emit the absolute path directly with forward slashes.
        abs_glob = str(pages_map[name]).replace("\\", "/") + "/*.tsx"
        lines.append(f"  {json.dumps(name)}: import.meta.glob<PageModule>({json.dumps(abs_glob)}),")
    lines.append("};")
    lines.append("")
    generated_text = "\n".join(lines)

    wrote_manifest = _write_if_changed(manifest_path, manifest_text)
    wrote_generated = _write_if_changed(generated_path, generated_text)

    if wrote_manifest or wrote_generated:
        logger.info(
            "Wrote module pages manifest: %d module(s) -> %s, %s",
            len(pages_map),
            manifest_path.name,
            generated_path.name,
        )
    return {"manifest": manifest_path, "generated": generated_path}


# ── Shared scaffold primitives ──────────────────────────────────────


def _module_to_pypi_name(name: str) -> str:
    """'Products' -> 'simple-module-products'. Matches the publishing convention."""
    return f"simple-module-{name.lower()}"


def _iter_template_files(template_root: Path):
    """Yield every file under ``template_root``, preserving relative paths."""
    for path in template_root.rglob("*"):
        if path.is_file():
            yield path


def _require_empty_dest(dest: Path) -> None:
    """Raise if ``dest`` is an existing non-empty directory — never clobber files."""
    if dest.exists() and any(dest.iterdir()):
        raise FileExistsError(
            f"Destination {dest} already exists and is non-empty. "
            "Choose a new path or remove the contents first."
        )
    dest.mkdir(parents=True, exist_ok=True)


def _resolve_template_root(subdir: str, override: Path | None) -> Path:
    """Return the scaffold template root, either from package data or an override."""
    if override is not None:
        return Path(override)
    return Path(str(importlib.resources.files(_TEMPLATES_PACKAGE) / subdir))


def _apply_template_files(
    src_root: Path,
    dest: Path,
    substitutions: Mapping[str, str],
    *,
    path_rewrites: Mapping[str, str] | None = None,
) -> None:
    """Copy every file under ``src_root`` to ``dest``, applying substitutions.

    Files ending in ``.tpl`` are read as text, placeholders replaced, and
    written without the suffix. Every other file is copied verbatim. If
    ``path_rewrites`` is given, each key is replaced by its value anywhere
    in relative paths (used by :func:`create_module` to rename the
    ``__PACKAGE__`` directory placeholder).
    """
    for src in _iter_template_files(src_root):
        rel_str = str(src.relative_to(src_root))
        for old, new in (path_rewrites or {}).items():
            rel_str = rel_str.replace(old, new)
        rel_str = rel_str.removesuffix(".tpl")
        target = dest / rel_str
        target.parent.mkdir(parents=True, exist_ok=True)

        if src.suffix == ".tpl":
            text = src.read_text(encoding="utf-8")
            for placeholder, value in substitutions.items():
                text = text.replace(placeholder, value)
            target.write_text(text, encoding="utf-8")
        else:
            shutil.copy2(src, target)


# ── Host scaffolding ────────────────────────────────────────────────


def create_host(
    dest: Path,
    name: str,
    modules: Sequence[str],
    template_root: Path | None = None,
) -> Path:
    """Materialize a SimpleModule host scaffold at ``dest``.

    Modules listed in ``modules`` become PyPI dependencies in the scaffolded
    ``pyproject.toml`` (e.g. ``"simple-module-products>=0.1,<1.0"``). Raises
    :class:`FileExistsError` if ``dest`` is an existing non-empty directory.
    """
    dest = Path(dest)
    _require_empty_dest(dest)

    module_dep_lines = "\n".join(f'    "{_module_to_pypi_name(m)}>=0.1,<1.0",' for m in modules)
    _apply_template_files(
        _resolve_template_root("host", template_root),
        dest,
        {"{{HOST_NAME}}": name, "{{MODULE_DEPS}}": module_dep_lines},
    )

    logger.info(
        "Scaffolded host '%s' at %s (modules: %s)", name, dest, ", ".join(modules) or "<none>"
    )
    return dest


# ── Module scaffolding ──────────────────────────────────────────────


def _to_snake_case(name: str) -> str:
    """'MyFeature' / 'my-feature' / 'My Feature' -> 'my_feature'."""
    s = re.sub(r"(?<!^)(?=[A-Z])", "_", name)
    s = re.sub(r"[\s\-]+", "_", s)
    return s.lower()


def _to_kebab_case(name: str) -> str:
    """'MyFeature' / 'my_feature' -> 'my-feature' (used as the PyPI slug)."""
    return _to_snake_case(name).replace("_", "-")


def _to_pascal_case(name: str) -> str:
    """'my-feature' / 'my_feature' -> 'MyFeature' (the display name in Meta)."""
    snake = _to_snake_case(name)
    return "".join(part.capitalize() for part in snake.split("_") if part)


def create_module(
    dest: Path,
    name: str,
    template_root: Path | None = None,
) -> Path:
    """Materialize a publishable module package at ``dest``.

    ``name`` is accepted in any case style (``MyFeature``, ``my-feature``,
    ``my_feature``) and normalized to three forms:

    * ``MODULE_NAME``  — ``PascalCase``, appears in ``Meta(name=...)``
    * ``MODULE_SLUG``  — ``kebab-case``, used in the PyPI distribution name
    * ``PACKAGE_NAME`` — ``snake_case``, the importable Python package and
      the entry_point key
    """
    dest = Path(dest)
    _require_empty_dest(dest)

    display_name = _to_pascal_case(name)
    slug = _to_kebab_case(name)
    package_name = _to_snake_case(name)

    _apply_template_files(
        _resolve_template_root("module", template_root),
        dest,
        substitutions={
            "{{MODULE_NAME}}": display_name,
            "{{MODULE_SLUG}}": slug,
            "{{PACKAGE_NAME}}": package_name,
        },
        path_rewrites={_PACKAGE_PATH_TOKEN: package_name},
    )

    logger.info("Scaffolded module '%s' at %s (package: %s)", display_name, dest, package_name)
    return dest
