"""Keep revisions autogenerated on SQLite portable to PostgreSQL (GH #342).

Autogenerate against the default SQLite database emits things Postgres rejects
or never sees, and neither ``alembic check`` nor the boot check notices:

* Boolean ``server_default`` rendered as ``sa.text('0')`` — Postgres refuses an
  integer default on a boolean column. :func:`rewrite_boolean_defaults` and
  :func:`render_boolean_default` emit ``sa.false()`` / ``sa.true()`` instead.
* Expression indexes (``lower(email)``) are skipped on SQLite because it cannot
  reflect them. :func:`warn_unverifiable_expression_indexes` says so loudly.
* ``op.drop_table`` leaves ``CREATE TYPE`` behind on Postgres, so a downgrade
  followed by an upgrade fails with ``DuplicateObject``. Use
  :func:`drop_enums_if_postgres` in the revision's ``downgrade``.

``simple_module_db.migrations`` wires the first two into the hooks every
``env.py`` already passes to Alembic.
"""

from __future__ import annotations

import logging
from collections.abc import Iterator
from typing import Any

import sqlalchemy as sa
from alembic.operations.ops import AddColumnOp, AlterColumnOp, CreateTableOp
from simple_module_core.diagnostics._expression_index import find_expression_indexes
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import DefaultClause
from sqlalchemy.sql.elements import ColumnElement, False_, TextClause, True_

logger = logging.getLogger("alembic.env")

_FALSE_LITERALS = frozenset({"0", "false"})
_TRUE_LITERALS = frozenset({"1", "true"})


def boolean_default_for(default: Any) -> ColumnElement[bool] | None:
    """Map a Boolean ``server_default`` spelled as 0/1/true/false to ``sa.false()``/``sa.true()``.

    Accepts a ``DefaultClause``, ``text()``, bare string, or SQLAlchemy
    ``true()``/``false()``; returns ``None`` when it is none of those literals.
    """
    arg = default.arg if isinstance(default, DefaultClause) else default
    if isinstance(arg, False_):
        return sa.false()
    if isinstance(arg, True_):
        return sa.true()
    text = arg.text if isinstance(arg, TextClause) else arg
    if not isinstance(text, str):
        return None
    literal = text.strip().strip("()").strip("'\"").lower()
    if literal in _FALSE_LITERALS:
        return sa.false()
    if literal in _TRUE_LITERALS:
        return sa.true()
    return None


def render_boolean_default(type_: str, obj: Any, autogen_context: Any) -> str | bool:
    """``render_item`` branch: render ``true()``/``false()`` defaults as such.

    SQLAlchemy compiles ``false()`` under SQLite to ``0``, which Alembic then
    renders as ``sa.text('0')``. Intercepting the ``server_default`` item keeps
    the portable expression the model declared.
    """
    if type_ != "server_default":
        return False
    arg = obj.arg if isinstance(obj, DefaultClause) else obj
    if not isinstance(arg, (True_, False_)):
        return False
    prefix = autogen_context.opts.get("sqlalchemy_module_prefix", "sa.")
    return f"{prefix}{'true' if isinstance(arg, True_) else 'false'}()"


def _iter_ops(container: Any) -> Iterator[Any]:
    for op in container.ops:
        yield op
        if hasattr(op, "ops"):
            yield from _iter_ops(op)


def rewrite_boolean_defaults(upgrade_ops: Any) -> int:
    """Rewrite integer-looking defaults on Boolean columns in a revision's op tree.

    Covers columns of ``create_table``, ``add_column`` and ``alter_column``
    (the latter via ``existing_type``). Returns the number rewritten.
    """
    changed = 0
    for op in _iter_ops(upgrade_ops):
        if isinstance(op, CreateTableOp):
            columns = [c for c in op.columns if isinstance(c, sa.Column)]
        elif isinstance(op, AddColumnOp):
            columns = [op.column]
        elif isinstance(op, AlterColumnOp):
            replacement = None
            if isinstance(op.existing_type or op.modify_type, sa.Boolean):
                replacement = boolean_default_for(op.modify_server_default)
            if replacement is not None:
                op.modify_server_default = replacement
                changed += 1
            continue
        else:
            continue
        for column in columns:
            if not isinstance(column.type, sa.Boolean) or column.server_default is None:
                continue
            replacement = boolean_default_for(column.server_default)
            if replacement is not None:
                column.server_default = DefaultClause(replacement)
                changed += 1
    return changed


def warn_unverifiable_expression_indexes(dialect_name: str | None, metadata: sa.MetaData) -> list:
    """Warn when autogenerating on SQLite while models declare expression indexes.

    A warning rather than an error: autogenerate also runs for ordinary,
    unrelated revisions, and failing every one of them for an index that is
    already in history would block normal work. The warning is emitted on every
    run, names each index, and ``alembic check`` on Postgres
    (``make migrations-roundtrip-pg``) is the real gate. Returns the
    ``(table, index)`` pairs it warned about.
    """
    if dialect_name != "sqlite":
        return []
    found = find_expression_indexes(metadata.tables.values())
    if not found:
        return []
    listing = "\n".join(f"    - {index} on {table}" for table, index in found)
    logger.warning(
        "\n%s\n"
        "WARNING: autogenerating on SQLite. SQLite cannot reflect expression indexes,\n"
        "so this revision does NOT account for the following (they are neither\n"
        "created nor verified here) and `alembic check` will not notice drift:\n"
        "%s\n"
        "Add them to the revision by hand and verify on PostgreSQL before merging\n"
        "(`make migrations-roundtrip-pg`). See docs/module-authoring.md, Migrations.\n"
        "%s",
        "=" * 78,
        listing,
        "=" * 78,
    )
    return found


def drop_enums_if_postgres(op: Any, *names: str) -> None:
    """Drop the named enum types on PostgreSQL; a no-op elsewhere.

    Call it at the end of ``downgrade()``, after the tables that use the types
    are dropped. ``op.drop_table`` leaves the ``CREATE TYPE`` behind, and
    autogenerate never emits the ``Enum.drop``, so without this a
    ``downgrade`` followed by an ``upgrade`` fails with ``DuplicateObject``.
    SQLite has no such object, which is why the round trip passes there.
    """
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for name in names:
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
