"""Helpers for Alembic integration with module-based metadata.

A host's ``migrations/env.py`` should call :func:`build_module_metadata` to
obtain the combined ``target_metadata`` for autogenerate, and
:func:`make_include_object` to obtain an ``include_object`` filter that
protects non-module tables from being touched by autogenerate.

This abstraction decouples the host from the import mechanics and is the
single place where a pip-installed module's ``<pkg>.models`` submodule gets
loaded — so every host scaffolded by ``smpy create-host`` behaves identically
whether the module was installed via workspace path, PyPI wheel, or
``pip install -e``.
"""

from __future__ import annotations

import importlib
import logging
from collections.abc import Callable, Sequence
from enum import StrEnum
from typing import Literal

import sqlalchemy as sa
from alembic.operations.ops import CreateIndexOp, CreateTableOp, DropIndexOp, DropTableOp
from simple_module_core import ModuleBase
from simple_module_core.discovery import discover_modules, get_module_package_name
from sqlalchemy import Column, Index, MetaData
from sqlalchemy.schema import SchemaItem

from simple_module_db.base import all_module_bases

logger = logging.getLogger(__name__)

# Matches alembic.context.configure's include_object signature exactly so
# type-checkers accept the returned filter without casts or ignores.
_SchemaItemType = Literal[
    "schema", "table", "column", "index", "unique_constraint", "foreign_key_constraint"
]
IncludeObjectFn = Callable[[SchemaItem, str | None, _SchemaItemType, bool, SchemaItem | None], bool]
ProcessRevisionDirectivesFn = Callable[[object, object, list], None]


def build_module_metadata(modules: Sequence[ModuleBase] | None = None) -> MetaData:
    """Import every installed module's ``models`` submodule and return combined MetaData.

    Returns a single :class:`MetaData` containing every ``Table`` declared by
    every installed module's SQLAlchemy models. Modules without a ``models``
    submodule are skipped without error.

    :param modules: Optional list of already-discovered modules. When ``None``,
        :func:`discover_modules` is called to find them. Callers that already
        have the list (e.g. an env.py that shares state with the app) should
        pass it in to avoid re-parsing entry_points and re-running the
        framework version check.
    """
    if modules is None:
        modules = discover_modules()
    for mod in modules:
        pkg = get_module_package_name(mod)
        try:
            importlib.import_module(f"{pkg}.models")
        except ModuleNotFoundError:
            logger.debug("No models submodule for module '%s' (pkg=%s)", mod.meta.name, pkg)

    combined = MetaData()
    for base in all_module_bases:
        for table in base.metadata.tables.values():
            table.to_metadata(combined)
    return combined


def make_include_object(
    metadata: MetaData,
    *,
    ignore_unmodeled_fks: bool = True,
) -> IncludeObjectFn:
    """Return an Alembic ``include_object`` filter scoped to the module tables.

    Call as ``context.configure(..., include_object=make_include_object(meta))``.
    The filter accepts only table names present in ``metadata``, preventing
    autogenerate from diffing — and potentially dropping — tables that exist
    in the database but aren't owned by any installed module (e.g. a user
    table added by the host developer outside the module system).

    :param ignore_unmodeled_fks: When ``True`` (default), foreign-key
        constraints that exist in the live DB but are absent from the SQLModel
        metadata are skipped instead of being emitted as ``op.drop_constraint``
        in the autogenerated migration. The framework's recommended pattern
        declares cross-module FKs at the migration level only (no Python-level
        relationship between modules), so those constraints look "unmodeled" to
        Alembic on every autogen run and would otherwise be silently dropped.
        Set to ``False`` to recover the prior, drop-on-sight behaviour.
    """
    allowlist = {t.name for t in metadata.tables.values()}

    def include_object(
        object: SchemaItem,
        name: str | None,
        type_: _SchemaItemType,
        reflected: bool,
        compare_to: SchemaItem | None,
    ) -> bool:
        if type_ == "table":
            return name in allowlist
        if ignore_unmodeled_fks and type_ == "foreign_key_constraint" and compare_to is None:
            return False
        parent_table = getattr(object, "table", None)
        if parent_table is not None:
            return parent_table.name in allowlist
        return True

    return include_object


def make_process_revision_directives(
    metadata: MetaData,
) -> ProcessRevisionDirectivesFn:
    """Return an Alembic ``process_revision_directives`` hook that re-adds
    expression-based indexes silently dropped by autogenerate.

    SQLAlchemy 2.0 can't reflect expression-based indexes (functional indexes
    like ``CREATE INDEX ... ON t (lower(email))``) under the SQLite dialect.
    Autogenerate guards against false-positive diffs there by *skipping* the
    index entirely — which is correct for an "existing table, can't tell if
    the index already exists" diff, but disastrous on initial CREATE TABLE:
    SQLite dev DBs end up without an index that production Postgres has.

    This hook walks each generated ``MigrationScript`` and, for every
    ``CreateTableOp`` whose target table has expression-based indexes in the
    metadata, appends a matching ``CreateIndexOp``. The reverse ``DropIndexOp``
    is inserted into ``downgrade_ops`` before the table drop for symmetry —
    not strictly required (dropping the table drops the index) but it keeps
    autogen output readable.

    Call as::

        context.configure(
            ...,
            process_revision_directives=make_process_revision_directives(target_metadata),
        )
    """
    expression_indexes: dict[str, list[Index]] = {}
    for table in metadata.tables.values():
        for index in table.indexes:
            if _index_is_expression_based(index):
                expression_indexes.setdefault(table.name, []).append(index)

    def process_revision_directives(context, revision, directives):
        if not expression_indexes:
            return
        for script in directives:
            upgrade_ops = getattr(script, "upgrade_ops", None)
            if upgrade_ops is not None:
                _inject_create_index_after_create_table(upgrade_ops, expression_indexes)
            downgrade_ops = getattr(script, "downgrade_ops", None)
            if downgrade_ops is not None:
                _inject_drop_index_before_drop_table(downgrade_ops, expression_indexes)

    return process_revision_directives


def _index_is_expression_based(index: Index) -> bool:
    """An index is expression-based when any of its expressions is not a plain ``Column``."""
    return any(not isinstance(expr, Column) for expr in index.expressions)


def _inject_create_index_after_create_table(upgrade_ops, expression_indexes) -> None:
    existing_index_names = {
        getattr(op, "index_name", None) for op in upgrade_ops.ops if isinstance(op, CreateIndexOp)
    }
    new_ops: list = []
    for op in upgrade_ops.ops:
        new_ops.append(op)
        if not isinstance(op, CreateTableOp):
            continue
        for index in expression_indexes.get(op.table_name, []):
            if index.name in existing_index_names:
                continue
            new_ops.append(CreateIndexOp.from_index(index))
            existing_index_names.add(index.name)
            logger.info(
                "Re-emitting expression-based index %r on %r — autogenerate "
                "skipped it (dialect can't reflect functional indexes).",
                index.name,
                op.table_name,
            )
    upgrade_ops.ops = new_ops


def _inject_drop_index_before_drop_table(downgrade_ops, expression_indexes) -> None:
    existing_drop_names = {
        getattr(op, "index_name", None) for op in downgrade_ops.ops if isinstance(op, DropIndexOp)
    }
    new_ops: list = []
    for op in downgrade_ops.ops:
        if isinstance(op, DropTableOp):
            for index in expression_indexes.get(op.table_name, []):
                if index.name in existing_drop_names:
                    continue
                new_ops.append(DropIndexOp(index.name, table_name=op.table_name))
                existing_drop_names.add(index.name)
        new_ops.append(op)
    downgrade_ops.ops = new_ops


def render_item(type_, obj, autogen_context):
    """Alembic ``render_item`` callback for SQLModel + extension types.

    * Collapses SQLModel's ``AutoString`` to ``sa.String`` so migrations don't
      need to ``import sqlmodel``.
    * Renders Python ``StrEnum`` columns with ``values_callable`` so the
      Postgres enum labels match the lowercase ``StrEnum`` values rather than
      SQLAlchemy's default of using uppercase attribute names. This means raw
      SQL like ``WHERE status = 'ready'`` actually works against the live DB.
    * Adds the necessary imports for ``fastapi_users_db_sqlalchemy.generics``
      and ``geoalchemy2`` types (rendered by their own classes elsewhere) so
      the generated migration is importable.

    Pass to :func:`alembic.context.configure` as ``render_item=render_item``.
    """
    if type_ != "type":
        return False
    cls_name = type(obj).__name__
    cls_module = type(obj).__module__ or ""
    imports = autogen_context.imports if autogen_context is not None else None

    if cls_name == "AutoString":
        length = getattr(obj, "length", None)
        return f"sa.String(length={length})" if length is not None else "sa.String()"

    if imports is not None and cls_module.startswith("fastapi_users_db_sqlalchemy"):
        imports.add("import fastapi_users_db_sqlalchemy.generics")
    if imports is not None and cls_module.startswith("geoalchemy2"):
        imports.add("import geoalchemy2")

    # Match by isinstance, not class-name string — a user-defined ``Enum``
    # class elsewhere in the project would otherwise be matched here and
    # render with ``values_callable`` against an unrelated ``enum_class``.
    if isinstance(obj, sa.Enum):
        python_type = getattr(obj, "enum_class", None)
        if isinstance(python_type, type) and issubclass(python_type, StrEnum):
            name = getattr(obj, "name", None) or python_type.__name__.lower()
            members = ", ".join(repr(m.value) for m in python_type)
            return (
                f"sa.Enum({members}, name={name!r}, values_callable=lambda e: [m.value for m in e])"
            )

    return False  # let alembic use its default rendering
