/**
 * Landing page for the public root (`/`).
 *
 * Scaffolded by `smpy new` so a fresh app boots straight to a friendly
 * page instead of a 404. Replace or restyle as your app's front door
 * takes shape — the only contract is that something renders at "/".
 */

type LandingProps = {
  isAuthenticated: boolean;
};

export default function Landing({ isAuthenticated }: LandingProps) {
  const primaryHref = isAuthenticated ? '/dashboard' : '/users/login';
  const primaryLabel = isAuthenticated ? 'Open dashboard' : 'Sign in';

  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col justify-center gap-8 px-6 py-16">
      <header className="space-y-3">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
          simple_module_py
        </p>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
          Your app is up.
        </h1>
        <p className="text-base text-muted-foreground sm:text-lg">
          This is the host's landing page — generated by{' '}
          <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-sm">smpy new</code>.
          Edit{' '}
          <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-sm">
            client_app/pages/Landing.tsx
          </code>{' '}
          to make it yours.
        </p>
      </header>

      <div className="flex flex-wrap gap-3">
        <a
          href={primaryHref}
          className="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
        >
          {primaryLabel}
        </a>
        <a
          href="https://github.com/antosubash/simple_module_python"
          className="inline-flex items-center justify-center rounded-md border border-border bg-background px-5 py-2.5 text-sm font-medium transition-colors hover:bg-secondary"
        >
          Read the docs
        </a>
      </div>

      <section className="rounded-xl border border-border bg-card p-5">
        <h2 className="mb-3 text-sm font-semibold">Next steps</h2>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li>
            Create an admin:{' '}
            <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-[13px] text-foreground">
              uv run smpy users create-admin
            </code>
          </li>
          <li>
            Scaffold a module:{' '}
            <code className="rounded bg-secondary px-1.5 py-0.5 font-mono text-[13px] text-foreground">
              smpy create-module orders --dest modules/orders
            </code>
          </li>
          <li>
            Sign in at{' '}
            <a href="/users/login" className="font-mono text-[13px] text-primary hover:underline">
              /users/login
            </a>{' '}
            and explore the dashboard.
          </li>
        </ul>
      </section>
    </main>
  );
}
