"""Portability of revisions autogenerated on SQLite (GH #342)."""

from __future__ import annotations

import logging
from types import SimpleNamespace

import pytest
import sqlalchemy as sa
from alembic.autogenerate import produce_migrations, render_python_code
from alembic.runtime.migration import MigrationContext
from simple_module_db.migration_portability import (
    boolean_default_for,
    drop_enums_if_postgres,
    warn_unverifiable_expression_indexes,
)
from simple_module_db.migrations import make_process_revision_directives, render_item
from sqlalchemy.dialects import postgresql


def _metadata(*, with_index: bool = False) -> sa.MetaData:
    md = sa.MetaData()
    extra = [sa.Index("ix_flags_email_lower", sa.text("lower(email)"))] if with_index else []
    sa.Table(
        "flags",
        md,
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", sa.String),
        sa.Column("a", sa.Boolean, server_default=sa.false(), nullable=False),
        sa.Column("b", sa.Boolean, server_default=sa.true(), nullable=False),
        sa.Column("c", sa.Boolean, server_default=sa.text("0"), nullable=False),
        sa.Column("d", sa.Boolean, server_default="1", nullable=False),
        sa.Column("n", sa.Integer, server_default=sa.text("0"), nullable=False),
        *extra,
    )
    return md


def _autogenerate(md: sa.MetaData) -> tuple[str, MigrationContext, object]:
    engine = sa.create_engine("sqlite://")
    with engine.connect() as conn:
        ctx = MigrationContext.configure(conn, opts={"render_item": render_item})
        script = produce_migrations(ctx, md)
        hook = make_process_revision_directives(md)
        hook(ctx, None, [script])
        code = render_python_code(
            script.upgrade_ops, render_item=render_item, migration_context=ctx
        )
    return code, ctx, script


def test_boolean_defaults_render_portably():
    code, _, _ = _autogenerate(_metadata())

    assert code.count("sa.false()") == 2  # a (declared false()) and c (text('0'))
    assert code.count("sa.true()") == 2  # b (declared true()) and d ('1')
    # The Integer column keeps its integer default: only Boolean columns change.
    assert "sa.Column('n', sa.Integer(), server_default=sa.text('0')" in code


@pytest.mark.parametrize(
    ("raw", "expected"),
    [
        (sa.text("0"), "false"),
        (sa.text("1"), "true"),
        ("0", "false"),
        ("1", "true"),
        ("false", "false"),
        ("true", "true"),
        ("'false'", "false"),
        (sa.text("(1)"), "true"),
        (sa.false(), "false"),
        (sa.DefaultClause(sa.text("0")), "false"),
        ("2", None),
        (sa.text("now()"), None),
        (None, None),
    ],
)
def test_boolean_default_for(raw, expected):
    result = boolean_default_for(raw)
    if expected is None:
        assert result is None
    else:
        assert str(result.compile(dialect=postgresql.dialect())) == expected


def test_expression_index_warning_on_sqlite(caplog):
    md = _metadata(with_index=True)
    with caplog.at_level(logging.WARNING, logger="alembic.env"):
        found = warn_unverifiable_expression_indexes("sqlite", md)

    assert found == [("flags", "ix_flags_email_lower")]
    assert "ix_flags_email_lower" in caplog.text
    assert "by hand" in caplog.text
    assert "PostgreSQL" in caplog.text


def test_expression_index_warning_silent_elsewhere(caplog):
    md = _metadata(with_index=True)
    with caplog.at_level(logging.WARNING, logger="alembic.env"):
        assert warn_unverifiable_expression_indexes("postgresql", md) == []
        assert warn_unverifiable_expression_indexes("sqlite", _metadata()) == []
    assert caplog.text == ""


def test_hook_warns_during_autogenerate_on_sqlite(caplog):
    with caplog.at_level(logging.WARNING, logger="alembic.env"):
        _autogenerate(_metadata(with_index=True))
    assert "ix_flags_email_lower" in caplog.text


def test_plain_column_index_is_not_flagged():
    md = sa.MetaData()
    sa.Table(
        "t",
        md,
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("x", sa.Integer),
        sa.Index("ix_t_x", "x"),
    )
    assert warn_unverifiable_expression_indexes("sqlite", md) == []


class _FakeOp:
    def __init__(self, dialect: str) -> None:
        self.bind = SimpleNamespace(dialect=SimpleNamespace(name=dialect))

    def get_bind(self):
        return self.bind


def test_drop_enums_noop_off_postgres(monkeypatch):
    calls: list = []
    monkeypatch.setattr(postgresql.ENUM, "drop", lambda self, *a, **k: calls.append(self.name))
    drop_enums_if_postgres(_FakeOp("sqlite"), "status")
    assert calls == []


def test_drop_enums_on_postgres(monkeypatch):
    calls: list = []

    def fake_drop(self, bind, checkfirst=True):
        calls.append((self.name, checkfirst))

    monkeypatch.setattr(postgresql.ENUM, "drop", fake_drop)
    drop_enums_if_postgres(_FakeOp("postgresql"), "status", "kind")
    assert calls == [("status", True), ("kind", True)]
