// AUTO-GENERATED by simple_module_hosting.i18n_manifest — do not edit by hand.
// Regenerate by booting the host in development mode.

export const keys = {
  auth: {
    errors: {
      missing_permission: "auth.errors.missing_permission",
      not_authenticated: "auth.errors.not_authenticated",
    },
  },
  host: {
    error: {
      forbidden_description: "host.error.forbidden_description",
      forbidden_title: "host.error.forbidden_title",
      generic_description: "host.error.generic_description",
      generic_title: "host.error.generic_title",
      go_back: "host.error.go_back",
      go_home: "host.error.go_home",
      not_found_description: "host.error.not_found_description",
      not_found_title: "host.error.not_found_title",
      server_error_description: "host.error.server_error_description",
      server_error_title: "host.error.server_error_title",
    },
    landing: {
      badge: "host.landing.badge",
      cta_dashboard: "host.landing.cta_dashboard",
      cta_docs: "host.landing.cta_docs",
      cta_get_started: "host.landing.cta_get_started",
      features: {
        auth_description: "host.landing.features.auth_description",
        auth_title: "host.landing.features.auth_title",
        devtools_description: "host.landing.features.devtools_description",
        devtools_title: "host.landing.features.devtools_title",
        diagnostics_description: "host.landing.features.diagnostics_description",
        diagnostics_title: "host.landing.features.diagnostics_title",
        inertia_description: "host.landing.features.inertia_description",
        inertia_title: "host.landing.features.inertia_title",
        module_system_description: "host.landing.features.module_system_description",
        module_system_title: "host.landing.features.module_system_title",
        schema_description: "host.landing.features.schema_description",
        schema_title: "host.landing.features.schema_title",
      },
      hero_subtitle: "host.landing.hero_subtitle",
      hero_title_line1: "host.landing.hero_title_line1",
      hero_title_line2: "host.landing.hero_title_line2",
    },
  },
  ui: {
    errors: {
      generic_description: "ui.errors.generic_description",
      generic_title: "ui.errors.generic_title",
      go_home_button: "ui.errors.go_home_button",
      reload_button: "ui.errors.reload_button",
    },
    switcher: {
      label: "ui.switcher.label",
    },
  },
} as const;
