"""Proves module-shipped CSS survives a real Tailwind build.

Every unit test around `render_modules_css` can stay green while Tailwind
emits nothing at all — the generated `@import` only pays off if Tailwind
resolves the path and keeps the rule. This is the one assertion that exercises
that whole chain, so it drives a genuine build rather than inspecting the
generated text.

Skipped where a build is impossible: CI's `python-tests` job installs Python
deps only (`make install-py`), so `node_modules` is absent there. The JS jobs
and local runs do have it.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]

pytestmark = [
    pytest.mark.skipif(
        not (REPO_ROOT / "node_modules").is_dir(),
        reason="node_modules absent — run `npm install` to exercise the real build",
    ),
    pytest.mark.skipif(shutil.which("npm") is None, reason="npm not on PATH"),
]


class TestModuleCssReachesBundle:
    def test_module_class_is_emitted_by_vite_build(self):
        """A class defined only in a module's styles.css appears in the built CSS.

        `.dashboard-stat-grid` is declared in modules/dashboard/dashboard/styles.css
        and referenced by no TSX anywhere, so it can only reach the bundle via the
        generated `@import` of that stylesheet.
        """
        subprocess.run(
            [
                "uv",
                "run",
                "--project",
                "host",
                "smpy",
                "host",
                "gen-pages",
                "--host-dir=host/client_app",
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        )

        generated = (REPO_ROOT / "host/client_app/modules.generated.css").read_text(
            encoding="utf-8"
        )
        dashboard_css = REPO_ROOT / "modules/dashboard/dashboard/styles.css"
        assert f'@import "{dashboard_css.as_posix()}" layer(components);' in generated, (
            f"gen-pages did not emit the dashboard stylesheet import:\n{generated}"
        )

        subprocess.run(["npm", "run", "build"], cwd=REPO_ROOT, check=True, capture_output=True)

        built = list((REPO_ROOT / "host/static/dist/assets").glob("*.css"))
        assert built, "no CSS emitted by the build"
        combined = "\n".join(p.read_text(encoding="utf-8") for p in built)
        assert "dashboard-stat-grid" in combined, (
            "module-shipped CSS did not reach the bundle — the generated "
            "@import most likely failed to resolve"
        )


# Written into a real module's pages/ so the host build treats it exactly like
# any other module page. Removed again in the fixture's teardown.
PROBE_MODULE_PAGES = REPO_ROOT / "modules/audit_log/audit_log/pages"
PROBE_PAGE = PROBE_MODULE_PAGES / "CrossModuleImportProbe.tsx"
PROBE_SOURCE = """\
// Generated by test_module_css_build.py — safe to delete.
import { DemoPlaceholders } from '@simple-module-py/dashboard/pages/components/DemoPlaceholders';

export default function CrossModuleImportProbe() {
  return <DemoPlaceholders totalUsers={0} />;
}
"""


@pytest.fixture
def cross_module_probe_page():
    """Add a page importing a sibling module by npm package name, then remove it."""
    PROBE_PAGE.write_text(PROBE_SOURCE, encoding="utf-8")
    try:
        yield PROBE_PAGE
    finally:
        PROBE_PAGE.unlink(missing_ok=True)


class TestCrossModuleImportResolves:
    def test_module_can_import_a_sibling_by_npm_package_name(self, cross_module_probe_page):
        """`@simple-module-py/<slug>/…` resolves to the sibling's package dir.

        Nothing in Node's own resolution makes this work. A wheel-installed
        module is not an npm workspace member at all, so it never lands in
        node_modules; a workspace member *is* symlinked, but onto the
        source-tree module root — one level above the Python package — so the
        subpath lands somewhere that does not exist. Both cases are covered by
        the `npm_name` aliases the host builds from modules.assets.json.

        This can only be caught by a real build: every unit test around
        `npm_name` stays green while the alias itself is missing or misaimed.
        """
        subprocess.run(
            [
                "uv",
                "run",
                "--project",
                "host",
                "smpy",
                "host",
                "gen-pages",
                "--host-dir=host/client_app",
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
        )

        result = subprocess.run(
            ["npm", "run", "build"], cwd=REPO_ROOT, capture_output=True, text=True
        )
        assert result.returncode == 0, (
            "build failed — a module could not import a sibling by npm package "
            f"name:\n{result.stderr[-2000:]}"
        )

        chunks = list((REPO_ROOT / "host/static/dist/assets").glob("CrossModuleImportProbe*.js"))
        assert chunks, "probe page produced no chunk"
        # Resolution really happened if the sibling's component was pulled in
        # rather than the import being dropped or stubbed out.
        assert any("DemoPlaceholders" in c.read_text(encoding="utf-8") for c in chunks), (
            "probe chunk does not reference the sibling module's component"
        )
