[project]
name = "permissions"
version = "0.1.0"
description = "The Permissions module"
authors = []
requires-python = ">=3.12"
dependencies = [
    "simple-module-core",
    "simple-module-db",
    "simple-module-hosting",
    "users",
]

[project.entry-points.simple_module]
permissions = "permissions.module:PermissionsModule"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
simple-module-core = { workspace = true }
simple-module-db = { workspace = true }
simple-module-hosting = { workspace = true }
users = { workspace = true }
