"""Host application entry point.

This file was generated by `smpy create-host`. Modules are discovered at boot
via entry_points; add them to this host's pyproject.toml to install them.
"""

import os
from pathlib import Path

from simple_module_core.dotenv import load_dotenv_into_environ

# Resolve the workspace root from this file's location so the web process
# behaves the same regardless of where uvicorn was launched (the scaffolded
# Makefile uses ``cd host && uvicorn main:app``, but ``uv run --project host``
# or a wheel deployment may run from elsewhere). chdir up front so cwd-relative
# paths in ``.env`` (e.g. ``sqlite+aiosqlite:///./host/app.db``) resolve
# consistently; load ``.env`` into ``os.environ`` so framework code reading
# ``os.environ.get("SM_…")`` directly sees the same values pydantic does.
_REPO_ROOT = Path(__file__).resolve().parent.parent
os.chdir(_REPO_ROOT)
load_dotenv_into_environ(_REPO_ROOT / ".env")

from simple_module_hosting import Settings, create_app
from simple_module_hosting.logging import setup_logging

from routes import router as host_router

settings = Settings()

setup_logging(
    level=settings.log_level,
    json_format=settings.log_format == "json",
)

app = create_app(settings)
app.include_router(host_router)

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=settings.is_development,
    )
