# {{HOST_NAME}}

A SimpleModule host application, generated by `sm create-host`.

## Quick start

```bash
# Install Python deps (framework + any modules listed in pyproject.toml)
uv sync

# Copy example env and adjust
cp .env.example .env

# First time only — initialize the migration history for the modules you
# picked. Inspect the generated file, then apply it.
alembic revision --autogenerate -m "initial schema"
alembic upgrade head

# Run the API
python main.py
```

Dev UI + API together (when you have a `client_app/` alongside this file):

```bash
make dev    # if you ship a Makefile; otherwise run vite + uvicorn in two shells
```

Apps scaffolded by `smpy new` also ship Docker assets — `make docker-up`
builds `docker/host.Dockerfile` and runs the full stack from
`docker-compose.yml` (services match your `--db` choice), applying
migrations on container start.

## Adding a module

```bash
# 1) install the module package (e.g. from PyPI)
uv add simple_module_my_module

# 2) generate & apply the migration (new tables + any schema changes)
alembic revision --autogenerate -m "add my-module"
alembic upgrade head

# 3) restart the host — the module's routes, menu items, permissions,
#    feature flags, events, and health checks register automatically
```

## Disabling a module without uninstalling it

Set `SM_MODULES_ENABLED` to a JSON array of the modules you want loaded:

```
SM_MODULES_ENABLED=["Auth","Products"]
```

Unlisted modules stay installed (so the existing DB schema is untouched)
but don't contribute any routes, registries, or lifecycle work.

## Upgrading the framework

Modules declare `requires_framework` in their `Meta`. If a module can't
work with your installed `simple_module_core` version, the host refuses
to boot with `FrameworkVersionError` listing the offending modules.
Upgrade or pin as appropriate.
